### ISSUE TITLE
Add custom validation

### ISSUE THREAD

**Issue by aparlato** [stamen/map-gl-style-lint-action#1]
Right now it looks like this repo mostly just runs the specs `validate` function on styles. We should add additional validation that would be widely useful like we include in specific repos since `validate` doesn't catch many style problems. Based on those repos I'm thinking of, this would include:
- validating color strings
- validating that layer properties meet the spec (no extraneous properties or properties in the wrong position like `layout` vs `paint`)

There are likely many more, but starting to get this set up to run with a script we can continue to add to would be valuable as we continue to run into scenarios that should be linted but aren't caught in the spec's `validation` function.

cc @ebrelsford

**Comment by ebrelsford** [comment]
I agree, I think this is separate to this action though. If you don't mind I'd prefer to talk through this in stamen/carto-tools#2
